DROP TABLE IF EXISTS books; 
CREATE TABLE books (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(250), isbn VARCHAR(250), author VARCHAR(250), stock INT Default 0, create_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS tags;
CREATE TABLE tags(tag_id INT AUTO_INCREMENT PRIMARY KEY, tag_name VARCHAR(100), create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

DROP table IF EXISTS tag_book;
CREATE TABLE tag_book(tag_book_id INT AUTO_INCREMENT PRIMARY KEY, book_id INT NOT NULL, tag_id INT NOT NULL, status INT DEFAULT 0, FOREIGN KEY(book_id) REFERENCES books(id), FOREIGN KEY(tag_id) REFERENCES tags(tag_id));

DROP table IF EXISTS book_serial;
CREATE TABLE book_serial(book_serial_id INT AUTO_INCREMENT PRIMARY KEY, book_id INT NOT NULL, book_serial_number INT NOT NULL, status INT DEFAULT 0, create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(book_id) REFERENCES books(id));

DROP table IF EXISTS book_ledger;
CREATE TABLE book_ledger(ledger_id INT AUTO_INCREMENT PRIMARY KEY, book_serial_id INT NOT NULL, book_id INT NOT NULL, user_id INT NOT NULL, from_date TIMESTAMP NOT NULL, to_date TIMESTAMP NOT NULL, return_date TIMESTAMP, create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(book_serial_id) REFERENCES book_serial(book_serial_id));

DROP TABLE IF EXISTS USER;
CREATE TABLE user(id INT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(50) NOT NULL, phone_number VARCHAR(20), create_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);